apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  creationTimestamp: "2025-12-03T12:07:20Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: wiz-integration-infra
    kustomize.toolkit.fluxcd.io/namespace: wiz
  name: wiz-kubernetes-integration
  namespace: wiz
  resourceVersion: "1607999196"
  uid: 31caafce-8819-4f6f-ac99-53beb121506b
spec:
  chart:
    spec:
      chart: wiz-kubernetes-integration
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: wiz-kubernetes-integration
        namespace: wiz
      version: 0.2.140
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 10m
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      wizApiToken:
        secret:
          create: false
          name: wiz-api-token
    wiz-admission-controller:
      enabled: true
      kubernetesAuditLogsWebhook:
        enabled: true
    wiz-kubernetes-connector:
      autoCreateConnector:
        clusterFlavor: AKS
        waitUntilInitialized: false
      enabled: true
      wiz-broker:
        enabled: true
status:
  conditions:
  - lastTransitionTime: "2025-12-03T12:17:37Z"
    message: Fulfilling prerequisites
    observedGeneration: 1
    reason: Progressing
    status: "True"
    type: Reconciling
  - lastTransitionTime: "2025-12-03T12:17:37Z"
    message: 'Could not determine release state: unable to determine state for release
      with status ''uninstalling'''
    observedGeneration: 1
    reason: StateError
    status: "False"
    type: Ready
  - lastTransitionTime: "2025-12-03T12:12:25Z"
    message: "Helm install failed for release wiz/wiz-kubernetes-integration with
      chart wiz-kubernetes-integration@0.2.140: failed pre-install: 1 error occurred:\n\t*
      timed out waiting for the condition"
    observedGeneration: 1
    reason: InstallFailed
    status: "False"
    type: Released
  - lastTransitionTime: "2025-12-03T12:17:26Z"
    message: "Helm uninstall remediation for release wiz/wiz-kubernetes-integration.v1
      with chart wiz-kubernetes-integration@0.2.140 failed: 1 error occurred:\n\t*
      timed out waiting for the condition"
    observedGeneration: 1
    reason: UninstallFailed
    status: "False"
    type: Remediated
  failures: 2
  helmChart: wiz/wiz-wiz-kubernetes-integration
  history:
  - chartName: wiz-kubernetes-integration
    chartVersion: 0.2.140
    configDigest: sha256:3f68cb4c6da3ec190b550b5e82e01f0b6d97e8a7c981d1b06f8a6fd8c298728c
    deleted: "2025-12-03T12:12:25Z"
    digest: sha256:f42cd0b2200f9cf4e7fb1ea325e314b177b0a7dab5441a8aa29e1d3b32ab7dd8
    firstDeployed: "2025-12-03T12:07:22Z"
    lastDeployed: "2025-12-03T12:07:22Z"
    name: wiz-kubernetes-integration
    namespace: wiz
    status: uninstalling
    version: 1
  installFailures: 1
  lastAttemptedConfigDigest: sha256:3f68cb4c6da3ec190b550b5e82e01f0b6d97e8a7c981d1b06f8a6fd8c298728c
  lastAttemptedGeneration: 1
  lastAttemptedReleaseAction: install
  lastAttemptedRevision: 0.2.140
  observedGeneration: -1
  storageNamespace: wiz
