apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    rollme.brokerHash: 115ba85431eeaf8db3ff2173aee02d16e67df1555d5e1ef74cfa7ac0d812cab2
    rollme.proxyHash: 7913f001e00a2427a96d0f28eb99f4f0192a9116857b4487931ea25bcb485f2a
  creationTimestamp: "2025-12-03T12:12:26Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: wiz-kubernetes-integration
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wiz-kubernetes-connector
    app.kubernetes.io/version: "2.9"
    helm.sh/chart: wiz-kubernetes-connector-3.5.1
  name: wiz-kubernetes-connector-delete-connector
  namespace: wiz
  resourceVersion: "1608050271"
  uid: 7dbb92cc-06e5-4cf2-a20f-db2feb32ff61
spec:
  backoffLimit: 1
  completionMode: NonIndexed
  completions: 1
  manualSelector: true
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      app.kubernetes.io/instance: wiz-kubernetes-integration
      app.kubernetes.io/name: wiz-kubernetes-connector
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: wiz-kubernetes-integration
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: wiz-kubernetes-connector
        app.kubernetes.io/version: "2.9"
        helm.sh/chart: wiz-kubernetes-connector-3.5.1
        wiz.io/component: delete-kubernetes-connector
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
                - amd64
      containers:
      - args:
        - delete-kubernetes-connector
        - --input-secrets-namespace
        - wiz
        - --input-secret-name
        - wiz-kubernetes-integration-connector
        command:
        - wiz-broker
        env:
        - name: CLI_FILES_AS_ARGS
          value: /var/api-client/clientToken,/var/api-client/clientId
        - name: LOG_LEVEL
          value: info
        - name: WIZ_ENV
        image: wiziopublic.azurecr.io/wiz-app/wiz-broker:2.9
        imagePullPolicy: Always
        name: wiz-connector-delete
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 10000
          runAsNonRoot: true
          runAsUser: 10000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/api-client
          name: api-client
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
      serviceAccount: wiz-auto-modify-connector
      serviceAccountName: wiz-auto-modify-connector
      terminationGracePeriodSeconds: 30
      volumes:
      - name: api-client
        secret:
          defaultMode: 420
          secretName: wiz-api-token
  ttlSecondsAfterFinished: 60
status:
  ready: 0
  startTime: "2025-12-03T13:08:07Z"
  terminating: 0
  uncountedTerminatedPods: {}
