apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  creationTimestamp: "2025-12-03T08:35:34Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: wiz-integration-infra
    kustomize.toolkit.fluxcd.io/namespace: wiz
  name: wiz-kubernetes-integration
  namespace: wiz
  resourceVersion: "1607783621"
  uid: 3f2e1502-dbe5-4b1f-af97-aee3a1b36a2c
spec:
  chart:
    spec:
      chart: wiz-kubernetes-integration
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: wiz-kubernetes-integration
        namespace: wiz
      version: 0.2.140
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 10m
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      wizApiToken:
        secret:
          create: false
          name: wiz-api-token
    wiz-admission-controller:
      enabled: true
      kubernetesAuditLogsWebhook:
        enabled: true
    wiz-kubernetes-connector:
      autoCreateConnector:
        clusterFlavor: AKS
      enabled: true
      wiz-broker:
        enabled: true
status:
  conditions:
  - lastTransitionTime: "2025-12-03T08:45:50Z"
    message: Fulfilling prerequisites
    observedGeneration: 1
    reason: Progressing
    status: "True"
    type: Reconciling
  - lastTransitionTime: "2025-12-03T08:45:50Z"
    message: 'Could not determine release state: unable to determine state for release
      with status ''uninstalling'''
    observedGeneration: 1
    reason: StateError
    status: "False"
    type: Ready
  - lastTransitionTime: "2025-12-03T08:40:39Z"
    message: "Helm install failed for release wiz/wiz-kubernetes-integration with
      chart wiz-kubernetes-integration@0.2.140: failed pre-install: 1 error occurred:\n\t*
      timed out waiting for the condition"
    observedGeneration: 1
    reason: InstallFailed
    status: "False"
    type: Released
  - lastTransitionTime: "2025-12-03T08:45:39Z"
    message: "Helm uninstall remediation for release wiz/wiz-kubernetes-integration.v1
      with chart wiz-kubernetes-integration@0.2.140 failed: 1 error occurred:\n\t*
      timed out waiting for the condition"
    observedGeneration: 1
    reason: UninstallFailed
    status: "False"
    type: Remediated
  failures: 2
  helmChart: wiz/wiz-wiz-kubernetes-integration
  history:
  - chartName: wiz-kubernetes-integration
    chartVersion: 0.2.140
    configDigest: sha256:11822f53c36469b821c26653498f9c06fd1845fa02504058c8b6bdd9aae2c849
    deleted: "2025-12-03T08:40:39Z"
    digest: sha256:898ae4659a967f214ba36cad58c5caeac3c73956f19ebe73fb76cd06e865d8bc
    firstDeployed: "2025-12-03T08:35:37Z"
    lastDeployed: "2025-12-03T08:35:37Z"
    name: wiz-kubernetes-integration
    namespace: wiz
    status: uninstalling
    version: 1
  installFailures: 1
  lastAttemptedConfigDigest: sha256:11822f53c36469b821c26653498f9c06fd1845fa02504058c8b6bdd9aae2c849
  lastAttemptedGeneration: 1
  lastAttemptedReleaseAction: install
  lastAttemptedRevision: 0.2.140
  observedGeneration: -1
  storageNamespace: wiz
