apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    rollme.proxyHash: 2cea6e5db60bc6c359f66eed88de758d066fc921633a82bed5d49c3dfb244db3
    rollme.wizApiTokenHash: 7005e57562e584922ae8e0932bb42581e1ba1d01b5bfdabe6a95a87c1604dd8d
  creationTimestamp: "2025-12-03T07:49:53Z"
  generation: 1
  labels:
    app.kubernetes.io/chartName: wiz-admission-controller
    app.kubernetes.io/instance: wiz-integration
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wiz-integration-wiz-admission-controller-uninstall
    app.kubernetes.io/version: "2.11"
    helm.sh/chart: wiz-admission-controller-3.12.1
    wiz.io/component: admission-controller-uninstall
  name: wiz-integration-wiz-admission-controller-uninstall
  namespace: wiz
  resourceVersion: "1607783242"
  uid: 214c8b3f-7065-4f74-a0c8-d4fcf488a10d
spec:
  activeDeadlineSeconds: 300
  backoffLimit: 1
  completionMode: NonIndexed
  completions: 1
  manualSelector: true
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      app.kubernetes.io/name: wiz-integration-wiz-admission-controller-uninstall
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/chartName: wiz-admission-controller
        app.kubernetes.io/instance: wiz-integration
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: wiz-integration-wiz-admission-controller-uninstall
        app.kubernetes.io/version: "2.11"
        helm.sh/chart: wiz-admission-controller-3.12.1
        wiz.io/component: admission-controller-uninstall
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
                - amd64
      containers:
      - command:
        - /usr/bin/wiz-admission-controller
        - uninstall
        env:
        - name: CLI_FILES_AS_ARGS
          value: /var/api-client/clientToken,/var/api-client/clientId
        - name: WIZ_ENV
        - name: LOG_LEVEL
          value: info
        - name: WIZ_RUNTIME_METADATA_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: WIZ_RUNTIME_METADATA_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: WIZ_TERMINATION_GRACE_PERIOD
          value: 60s
        - name: WIZ_CHART_VERSION
          value: 3.12.1
        - name: WIZ_GLOBAL_LEADER_LEASE_NAME
          value: wiz-admission-controller-global-lease
        - name: WIZ_SCRAPE_API_SERVER_METRICS_ENABLED
          value: "true"
        image: wiziopublic.azurecr.io/wiz-app/wiz-admission-controller:2.11
        imagePullPolicy: Always
        name: wiz-admission-controller-uninstall
        resources: {}
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/api-client
          name: api-client
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: api-client
        secret:
          defaultMode: 420
          secretName: wiz-api-token
  ttlSecondsAfterFinished: 60
status:
  active: 1
  ready: 0
  startTime: "2025-12-03T08:45:31Z"
  terminating: 0
  uncountedTerminatedPods: {}
