apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wiz-sensor
  namespace: wiz-system
spec:
  interval: 30m
  chart:
    spec:
      chart: wiz-kubernetes-connector
      version: '>=1.0.0'
      sourceRef:
        kind: HelmRepository
        name: wiz-sec
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Values will be customized per environment
  values:
    # Common base values
    image:
      pullPolicy: IfNotPresent

    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000

    # Pod security
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
