apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wiz-kubernetes-integration
  namespace: wiz-system
spec:
  interval: 10m
  chart:
    spec:
      chart: wiz-kubernetes-integration
      version: 0.2.140
      sourceRef:
        kind: HelmRepository
        name: wiz-kubernetes-integration
        namespace: wiz-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      wizApiToken:
        secret:
          create: false
          name: wiz-api-token

    wiz-kubernetes-connector:
      enabled: true
      autoCreateConnector:
        clusterFlavor: AKS
      Wiz-broker:
        enabled: true

    wiz-admission-controller:
      enabled: true
      kubernetesAuditLogsWebhook:
        enabled: true
