apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wiz-integration
  namespace: wiz
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: wiz-kubernetes-integration
      version: 0.2.142  # Latest version
      sourceRef:
        kind: HelmRepository
        name: wiz-sec
        namespace: wiz
      interval: 10m
  install:
    createNamespace: false  # Namespace already exists
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      wizApiToken:
        secret:
          create: false
          name: wiz-api-token
    wiz-kubernetes-connector:
      enabled: true
      wizApiToken:
      autoCreateConnector:
        clusterFlavor: AKS
      Wiz-broker:
        enabled: true
    wiz-admission-controller:
      enabled: true
      wizApiToken:
        secret:
          create: false
          name: wiz-api-token
      kubernetesAuditLogsWebhook:
        enabled: true